### ISSUE TITLE
Regression: Creator & Project fields no longer set for new tickets

### ISSUE THREAD

**Issue by gwatts** [linear/linear-zapier#24]
We have a couple of Zaps  - One that sends a message to chat when a new ticket is created, and another that sends one when a ticket is updated.

During a previous update to the Zapier integration, we lost the "Creator" and "Project" fields for new ticket notifications; they're always blank now, including when the sample data is fetched during Zap setup:

![image](https://user-images.githubusercontent.com/334535/178574227-d05dc3cc-f349-4e30-ac70-bfb69393502b.png)

I can't see any other fields that contain the same data; perhaps i'm missing something?

**Comment by francoislevesque** [comment]
We have the same issue, we need the project name to sync Issues with Clockify using Zapier.
