### ISSUE TITLE
Regression: "Updated Issue in Linear" trigger no longer contains issue status

### ISSUE THREAD

**Issue by Matias-A** [linear/linear-zapier#28]
Last week, Zapier required us to update the deprecated "Linear for version 2.1.3" app to the newer version "Linear Beta". We're using the app to automatically create tickets and send an update on Slack whenever their status changes. However, after changing to the new version, it seems that the status field no longer exists in the trigger response. This unfortunately means that the status change monitoring is broken.

<img width="198" alt="Screenshot 2022-10-25 at 11 30 56" src="https://user-images.githubusercontent.com/8319613/197724227-515ef620-1959-40e4-bdaf-6d2056dc77d9.png">

Is this an intended change, or is there a workaround?

**Comment by alexbchr** [comment]
This definitely makes it hard to handle status change events using Zapier, which for me is the main reason I use the Linear App in Zapier.

**Comment by Matias-A** [comment]
Yep! still having the same issue. We've since implemented the same behavior with custom web hooks, but it feels dumb too considering this functionality used to exist 😅

**Comment by urossmolnik** [comment]
Status field was added back
