### ISSUE TITLE
[Feature Request] Ability to grab latest comment

### ISSUE THREAD

**Issue by anthonysnyder** [linear/linear-zapier#34]
I have no idea if I am doing this right, but I am hoping to have the Zapier integration updated so that one of the fields that I can pull data from is the latest comment on a ticket.

My use case here is if I update a ticket in Linear via a new comment, I want to be grab that comment and (via Zapier) add it to a database entry in Notion.

**Comment by tommoor** [comment]
It sounds like you need to switch to using the existing comment trigger,

![image](https://user-images.githubusercontent.com/380914/208779167-6969210e-0dd7-4183-b6ab-75c480ecde54.png)

You can see the data that will be available for new comments, here:

https://github.com/linear/linear-zapier/blob/master/src/triggers/comment.ts#L4

**Comment by anthonysnyder** [comment]
O.o

How did I miss that?

**Comment by anthonysnyder** [comment]
Ah, yes. So I am not sure if this is desired functionality, but when I try and do that, the **Issue ID** field does not allow me to "Insert Data" like using the Updated Issue trigger does ala this screenshot. 
![image](https://user-images.githubusercontent.com/16548221/208780364-a770d965-1776-4013-919b-99af69c23c27.png)

As I am writing this comment, it would also be convenient if I could choose a label to trigger off of. 

Such as: New comment added to a ticket with the XX label but ignore all other new comments.

**Comment by tommoor** [comment]
It should be there according to the code…
