### ISSUE TITLE
Quinn test 2

### ISSUE THREAD

**Issue by quinn-linear** [linear/linear-zapier#55]
Test @tommoor #54 

- [ ] one
- [ ] two
[ ] 1

`codetest`

### Heading
[Uploading choosy_2.3.1.zip…]()

**Comment by quinn-linear** [comment]
[Uploading choosy_2.3.1.zip…]()

**Comment by quinn-linear** [comment]
https://github.com/linear/linear-zapier/assets/97164745/55f91fe7-e52f-41fa-80e7-8f8fc1743359

**Comment by quinn-linear** [comment]
comment

**Comment by pauldijou** [comment]
Yo
