### ISSUE TITLE
Create a new label from Zapier

### ISSUE THREAD

**Issue by SharbelOkzan** [linear/linear-zapier#63]
Is it currently possible to create a new Linear label from a Zap?

If not, I hope this is a considerable feature request.

**Comment by rubiconjosh** [comment]
I do not believe this is currently supported. The below screenshot from the Zapier/Linear Integration page (https://zapier.com/apps/linear/integrations) only shows two Actions..

<img width="1196" alt="Screenshot 2024-07-10 at 2 48 32 PM" src="https://github.com/linear/linear-zapier/assets/6276885/04fca756-666e-48b0-bf97-9033ba181a0c">

This would be a valuable feature for my workflow.

I am surprised I can not create a comment on a LInear Issue that adds a label such as `/label released`
